name: Release

on:
  push:
    tags:
      - '*' # Déclenche l'action sur la création de n'importe quel tag

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Requis pour créer une release GitHub
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }} # Nom de la release = Nom du tag
          files: build/libs/*.jar # Ajoute le/les fichiers .jar générés
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
